Gp/ci optimization
HorizenLabs/zkVerify pull request #119
Opened 2024-08-22 10:58 UTC by JackPiri

This PR introduces the following improvements for the CI (sorted by commit history):

- introduction of a Python script (`profile-CI.py`) for automatic profiling of CI runs,
- refactoring of script (`clean_ci.sh`) for cleaning GitHubActions runner; now the N largest packages are removed (instead of an hard-coded list),
- `docker-job` and Crustdoc-job` now run in parallel, since they are independent,
- removal of on-demand run trigger for workflows that should be triggered only by other workflows,
- changes to caches management; now:
  - each Sunday at 0:00 UTC a workflow (`Cache manager`) runs on `main` branch; it deletes all caches and executes the build, test, coverage and lint-format jobs saving the corresponding caches (write-only),
  - every run of `Orchestrator` and `Tag-orchestrator` runs restoring the available caches (read-only),
  - in this way the frequent runs of `Orchestrator` always have a recent cache available (7 days old at worst),
- refactoring for `End-to-end-test` job, now using `build-cache`,
- refactoring for `Build-and-Test` job (now split in `Build` job and `Test` job),
- other minor fixes.

Currently the profiling of 12 recent runs (244, 245, 246, 249, 250, 251, 252, 253, 256, 257, 259, 260) is reported in this table:

| Job | Average execution time (s) |
| - | - |
| build-test-job / build-and-test | 2423.75 |
| e2e-test-job / e2e-test | 2137.75 |
| lint-format-job / lint-and-format | 1489 |
| test-coverage-job / coverage | 2357.75 |

the `build-test-job / build-and-test` being the bottleneck.

The plan is to analyse again the situation on some future CI runs after this PR is merged.

2024-09-02 10:36 UTC, la10736 requested changes
I guess we need to cache also `config.toml` and maybe we can remove ci-clean.sh at all.

2024-09-02 10:36 UTC, la10736 commented on .github/workflows/CI-coverage.yml
>            path: |
See my other comment about cache `config.toml`

2024-09-02 10:36 UTC, la10736 commented on .github/workflows/CI-e2e-test.yml
>            path: |
See my other comment about cache `config.toml`

2024-09-02 10:36 UTC, la10736 commented on .github/workflows/CI-lint-format.yml
>            path: |
See my other comment about cache `config.toml`

2024-09-02 10:36 UTC, la10736 commented on .github/workflows/CI-rustdoc.yml
>            path: |
See my other comment about cache `config.toml`

2024-09-02 10:36 UTC, la10736 commented on .github/workflows/CI-test.yml
>          with:
See my other comment about cache `config.toml`

2024-09-04 10:23 UTC, JackPiri commented on .github/scripts/clean_ci.sh
> +# sudo rm -rf /usr/local/.ghcup
Sure, removed the commented lines.

2024-09-04 10:24 UTC, JackPiri commented on .github/workflows/CI-build.yml
> +            deps/
Actually this should be not an issue.
During no-cache runs (`CI-cache-manager`) you get:
- full build, `target` folder gets populated
- nothing is placed into `deps` folder
- nothing is written into `~/.cargo/config.toml`
- cache is saved (`target` folder among the others)
During cache runs (`CI-orchestrator`) you get:
- cache is restored (`target` folder among the others)
- partial build, lib dependencies are present and copied from `target` to `deps` and finally linked

2024-09-04 12:03 UTC, JackPiri commented on .github/scripts/clean_ci.sh
>  echo "********************************* START SIZE *********************************"
My first feeling was that the script was still needed, but actually checking without running it I got 19GB before building and 11GB after building. Let's opt for removing the usage of `clean_ci.sh` and keep an eye open on it for the next weeks.

2024-09-04 15:15 UTC, la10736 commented on .github/workflows/CI-build.yml
> +            deps/
Fine

2024-09-04 16:53 UTC, rdoria1 approved these changes
LGTM

2024-09-05 07:32 UTC, JackPiri commented
> LGTM
> 
> Just a question, what happens if the caching job running on sunday fails? (after all the caches were deleted) Is there a retry policy? Will the other steps continue to run despite the cache potentially not being available ?
> 
> Also https://github.com/HorizenLabs/zkVerify/actions/runs/10706082369 failed, coverage job skipped, is that the reason? I don't see any other error
> 
> Also rebase with main is needed

In case the Sunday `cache-manager` run fails no cache is saved and consequently no cache is restored by the other CI runs, this eventually resulting in those runs being slower (until next week).
The skipped `coverage-job` is quite weird, it didn't start at all; I guess/hope it's a transient error, let me try re-running.
Ok for rebasing.

2024-09-05 08:24 UTC, JackPiri commented
@la10736 actually I have to reconsider the full removal of `clean_ci.sh`; on `CI-coverage` job I am getting an error _No space left on device_ (https://github.com/HorizenLabs/zkVerify/actions/runs/10715945218) so I need to reintroduce it there; still keeping disabled for the other two jobs (`CI-build` and `CI-test`).

2024-09-05 09:07 UTC, merged