Md/vk
HorizenLabs/zkVerify pull request #63
Opened 2024-05-28 13:54 UTC by la10736

Implements [ZKV-230](https://horizenlabs.atlassian.net/browse/ZKV-230)

Introduce the exstrinsic for registring Vk and add an optional (for retro campatibility) variant `VkOrHash` to submit the proof. 

Also add E2E tests and refactor athe E2E tests little bit.

2024-05-29 12:18 UTC, DanieleDiBenedetto requested changes
Minor changes. Not a fan of the default vk in case not specified though

2024-05-29 12:18 UTC, DanieleDiBenedetto commented on e2e-tests/README.md
> +debug flavor you can use `--debug` switch. Follow line execute all tests running the node binary
```suggestion
debug flavor you can use `--debug` switch. The following line executes all the tests running the node binary
```

2024-05-29 12:18 UTC, DanieleDiBenedetto commented on e2e-tests/README.md
> +You can run a list of tests simply by indicate the names while running tests:
```suggestion
You can run a list of tests by simply specifying the names while running the tests:
```

2024-05-30 12:13 UTC, la10736 commented on pallets/settlement-fflonk/src/lib.rs
> +    const PREFIX: &[u8; 6] = b"fflonk";
No, take a look to line 181 and 178 that add this character correctly.

2024-05-30 12:17 UTC, la10736 reviewed
> Minor changes. Not a fan of the default vk in case not specified though 

Me too, but I've used this trick to make a smoother transaction... I'll remove it when I'll abstract the verifier.

2024-05-30 12:54 UTC, DanieleDiBenedetto approved these changes

2024-05-31 15:23 UTC, drgora approved these changes
Nice refactoring for e2e tests, thanks!
This looks good to me, I just left two comments/clarification questions, but nothing blocking

2024-06-03 11:13 UTC, la10736 commented on pallets/settlement-fflonk/src/lib.rs
> +        pub fn register_vk(_origin: OriginFor<T>, vk: Box<Vk>) -> DispatchResultWithPostInfo {
Yes we had.

We're inheriting it from ` #[pallet::call(weight(<T as Config>::WeightInfo))]` impl's attribute: if the weight trait have a method that match with our extrinsic it uses this method.

2024-06-03 11:21 UTC, la10736 commented on e2e-tests/js_scripts/0007-proof_with_vk.js
> +
Right, I'll fix it! 
THX!

2024-06-04 10:22 UTC, merged